name: flutter_custom_calendar
description: A new Flutter calendar package.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  scoped_model: ^2.0.0
  shamsi_date: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

